name: "Publish Python distribution to PyPI Test"
# Uses:
# https://github.com/actions/setup-python : a26af69be951a213d495a4c3e4e4022e16d87065
# https://github.com/actions/checkout : 11bd71901bbe5b1630ceea73d27597364c9af683
# https://github.com/actions/download-artifact : d3f86a106a0bac45b974a628896c90dbdf5c8093
# https://github.com/actions/upload-artifact : ea165f8d65b6e75b540449e92b4886f43607fa02
# https://github.com/actions/pypa/gh-action-pypi-publish : 76f52bc884231f62b9a034ebfe128415bbaabdfc

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[a-z]+[0-9]+"

jobs:
  build:
    name: "Build package"
    runs-on: "ubuntu-latest"
    outputs:
      artifact-id: "${{ steps.upload-artifact.outputs.artifact-id }}"

    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: "actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065"
        with:
          python-version: "3.12"

      - name: "Build the package"
        run: "python -m pip install nox; nox -s build"

      - name: "Store the distribution packages"
        id: "upload-artifact"
        uses: "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02"
        with:
          path: "./dist"

  publish-to-pypi:
    name: "Publish Python Distribution to PyPI"
    needs: ["build"]
    runs-on: "ubuntu-latest"
    environment:
      name: "testpypi"
      url: "https://test.pypi.org/project/commented-configparser/"
    permissions:
      id-token: "write"

    steps:
      - name: "Download all the dists"
        uses: "actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093"
        with:
          artifact-ids: "${{ needs.build.outputs.artifact-id }}"
          path: "./dist"
          merge-multiple: true

      - name: "Publish distribution to PyPI"
        uses: "pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc"
        with:
          repository-url: "https://test.pypi.org/legacy/"
          verbose: true
